//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("adresse")]
    public partial class Adresse : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Adresse()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Universel, unik identifikation af adressen af datatypen UUID. Er stabil over hele adressens levetid (ligesom et CPR-nummer) dvs. uanset om adressen evt. ændrer vejnavn, husnummer, postnummer eller kommunekode. Repræsenteret som 32 hexadecimale tegn. Eksempel: ”0a3f507a-93e7-32b8-e044-0003ba298018”.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("id")]
        [Required()]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Adressens status. Heltal. Mulige værdier er 1: gældende, 2: nedlagt, 3: foreløbig, 4: henlagt.
        /// </summary>
        
        [Column("status")]
        [Required()]
        public virtual int Status { get; set; }

        /// <summary>
        /// Dato og tid for adressens oprettelse, som registreret hos DAR. Eksempel: 2001-12-23T00:00:00.
        /// </summary>
        
        [Column("oprettet")]
        [Required()]
        public virtual DateTime Oprettet { get; set; }

        /// <summary>
        /// Dato og tid hvor der sidst er ændret i adressen, som registreret hos DAR. Eksempel: 2002-04-08T00:00:00.
        /// </summary>
        
        [Column("ændret")]
        [Required()]
        public virtual DateTime Ændret { get; set; }

        /// <summary>
        /// Adressens ikrafttrædelsesdato, dvs. det tidspunkt hvor adressen først er registreret som "gældende" i DAR. Kan være fremtidig.
        /// </summary>
        
        [Column("ikrafttrædelsesdato")]
        public virtual DateTime? Ikrafttrædelsesdato { get; set; }

        /// <summary>
        /// Identifier for adressens adgangsadresse. UUID.
        /// </summary>
        
        [Column("adgangsadresseid")]
        [Required()]
        public virtual Guid Adgangsadresseid { get; set; }

        /// <summary>
        /// Etagebetegnelse. Hvis værdi angivet kan den antage følgende værdier: tal fra 1 til 99, st, kl, k2 op til k99.
        /// </summary>
        
        [Column("etage", TypeName = "varchar(3)")]
        public virtual string Etage { get; set; }

        /// <summary>
        /// Dørbetegnelse. Hvis værdi angivet kan den antage følgende værdier: tal fra 1 til 9999, små bogstaver samt tegnene / og -.
        /// </summary>
        
        [Column("dør", TypeName = "varchar(6)")]
        public virtual string Dør { get; set; }

        /// <summary>
        /// Kode der angiver kilden til adressen. Tal bestående af et ciffer.
        /// </summary>
        
        [Column("kilde")]
        public virtual int? Kilde { get; set; }

        /// <summary>
        /// Nøgle i ESDH system.
        /// </summary>
        
        [Column("esdhreference", TypeName = "varchar(1000)")]
        public virtual string Esdhreference { get; set; }

        /// <summary>
        /// Journalnummer.
        /// </summary>
        
        [Column("journalnummer", TypeName = "varchar(1000)")]
        public virtual string Journalnummer { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Id.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
