//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("bbr_bygning_historik")]
    public partial class Bbr_bygning_historik : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Bbr_bygning_historik()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Unik ID for den angivne række. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("rowkey")]
        [Required()]
        public virtual int Rowkey { get; set; }

        /// <summary>
        /// Startidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningstart")]
        [Required()]
        public virtual DateTime Virkningstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens virkningstid. 
        /// </summary>
        
        [Column("virkningslut")]
        public virtual DateTime? Virkningslut
        {
            get { return _Virkningslut.GetValueOrDefault(Defaults.Virkningslut); }
            set { _Virkningslut = value; }
        }
        private DateTime? _Virkningslut;

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Forretningshaendelse">kodelisten.</a>
        /// </summary>
        
        [Column("forretningshændelse", TypeName = "varchar(50)")]
        public virtual string Forretningshændelse { get; set; }

        /// <summary>
        /// FORM-kode for det offentlige forretningsområde som har opdateret bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsOmraade">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsområde", TypeName = "varchar(15)")]
        public virtual string Forretningsområde { get; set; }

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsProcess">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsproces", TypeName = "varchar(2)")]
        public virtual string Forretningsproces { get; set; }

        /// <summary>
        /// Unik og uforanderlig identifikation af bygværkselementet igennem hele dets livscyklus
        /// </summary>
        
        [Column("id")]
        public virtual Guid? Id { get; set; }

        /// <summary>
        /// Kode der identificerer den kommune som bygværkselementet hidhører For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Kommunekode">kodelisten.</a>
        /// </summary>
        
        [Column("kommunekode", TypeName = "varchar(4)")]
        public virtual string Kommunekode { get; set; }

        /// <summary>
        /// Kode som angiver hvilken aktør der har foretaget registreringen af den pågældende version af bygværkselementet
        /// </summary>
        
        [Column("registreringsaktør", TypeName = "varchar(90)")]
        public virtual string Registreringsaktør { get; set; }

        /// <summary>
        /// Kode for bygværkselementets status i den pågældende version, dvs. elementets tilstand i den samlede livscyklus For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Livscyklus">kodelisten.</a>
        /// </summary>
        
        [Column("status", TypeName = "varchar(2)")]
        public virtual string Status { get; set; }

        /// <summary>
        /// Kode for den aktør der har afstedkommet virkningsegenskaberne for den pågældende version af bygværkselementet For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Virkningsakt%C3%B8r">kodelisten.</a>
        /// </summary>
        
        [Column("virkningsaktør", TypeName = "varchar(90)")]
        public virtual string Virkningsaktør { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("jordstykke")]
        public virtual int? Jordstykke { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("husnummer")]
        public virtual Guid? Husnummer { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("ejerlejlighed")]
        public virtual Guid? Ejerlejlighed { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("grund")]
        public virtual Guid? Grund { get; set; }

        /// <summary>
        /// Angiver bygningens nummer indenfor vurderingsejendommen
        /// </summary>
        
        [Column("byg007Bygningsnummer")]
        public virtual int? Byg007Bygningsnummer { get; set; }

        /// <summary>
        /// Angiver bygningens hovedanvendelse For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/BygAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("byg021BygningensAnvendelse", TypeName = "varchar(3)")]
        public virtual string Byg021BygningensAnvendelse { get; set; }

        /// <summary>
        /// Antal lejligheder med køkken i bygning
        /// </summary>
        
        [Column("byg024AntalLejlighederMedKøkken")]
        public virtual int? Byg024AntalLejlighederMedKøkken { get; set; }

        /// <summary>
        /// Antal lejligheder uden køkken i bygning.
        /// </summary>
        
        [Column("byg025AntalLejlighederUdenKøkken")]
        public virtual int? Byg025AntalLejlighederUdenKøkken { get; set; }

        /// <summary>
        /// Angiver bygningens opførselsår.
        /// </summary>
        
        [Column("byg026Opførelsesår")]
        public virtual int? Byg026Opførelsesår { get; set; }

        /// <summary>
        /// Angiver bygningens seneste om- eller tilbygningsår.
        /// </summary>
        
        [Column("byg027OmTilbygningsår")]
        public virtual int? Byg027OmTilbygningsår { get; set; }

        /// <summary>
        /// Angiver udløbsdato for midlertidig opført bygning.
        /// </summary>
        
        [Column("byg029DatoForMidlertidigOpførtBygning")]
        public virtual DateTime? Byg029DatoForMidlertidigOpførtBygning { get; set; }

        /// <summary>
        /// Angiver bygningens vandforsyning. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Vandforsyning">kodelisten.</a>
        /// </summary>
        
        [Column("byg030Vandforsyning", TypeName = "varchar(1)")]
        public virtual string Byg030Vandforsyning { get; set; }

        /// <summary>
        /// Angiver bygningens afløbsforhold. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Afloebsforhold">kodelisten.</a>
        /// </summary>
        
        [Column("byg031Afløbsforhold", TypeName = "varchar(3)")]
        public virtual string Byg031Afløbsforhold { get; set; }

        /// <summary>
        /// Angiver bygningens ydervægsmateriale. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/YdervaeggenesMateriale">kodelisten.</a>
        /// </summary>
        
        [Column("byg032YdervæggensMateriale", TypeName = "varchar(2)")]
        public virtual string Byg032YdervæggensMateriale { get; set; }

        /// <summary>
        /// Angiver bygningens tagdækningsmateriale. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Tagdaekningsmateriale">kodelisten.</a>
        /// </summary>
        
        [Column("byg033Tagdækningsmateriale", TypeName = "varchar(2)")]
        public virtual string Byg033Tagdækningsmateriale { get; set; }

        /// <summary>
        /// Angiver bygningens supplerende ydervægsmateriale. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/YdervaeggenesMateriale">kodelisten.</a>
        /// </summary>
        
        [Column("byg034SupplerendeYdervæggensMateriale", TypeName = "varchar(2)")]
        public virtual string Byg034SupplerendeYdervæggensMateriale { get; set; }

        /// <summary>
        /// Angiver bygningens supplerende tagdækningsmateriale. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Tagdaekningsmateriale">kodelisten.</a>
        /// </summary>
        
        [Column("byg035SupplerendeTagdækningsMateriale", TypeName = "varchar(2)")]
        public virtual string Byg035SupplerendeTagdækningsMateriale { get; set; }

        /// <summary>
        /// Angivelse af om der er  konstateret asbestholdigt materiale i ydervæg eller tagdækning. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/AsbestholdigtMateriale">kodelisten.</a>
        /// </summary>
        
        [Column("byg036AsbestholdigtMateriale", TypeName = "varchar(1)")]
        public virtual string Byg036AsbestholdigtMateriale { get; set; }

        /// <summary>
        /// Angiver kilde til bygningens materialer. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KildeTilOplysninger">kodelisten.</a>
        /// </summary>
        
        [Column("byg037KildeTilBygningensMaterialer", TypeName = "varchar(1)")]
        public virtual string Byg037KildeTilBygningensMaterialer { get; set; }

        /// <summary>
        /// Angiver bygningens samlede areal.
        /// </summary>
        
        [Column("byg038SamletBygningsareal")]
        public virtual int? Byg038SamletBygningsareal { get; set; }

        /// <summary>
        /// Angiver bygningens samlede boligareal.
        /// </summary>
        
        [Column("byg039BygningensSamledeBoligAreal")]
        public virtual int? Byg039BygningensSamledeBoligAreal { get; set; }

        /// <summary>
        /// Angiver bygningens samlede erhvervsareal.
        /// </summary>
        
        [Column("byg040BygningensSamledeErhvervsAreal")]
        public virtual int? Byg040BygningensSamledeErhvervsAreal { get; set; }

        /// <summary>
        /// Angiver bygningens bebyggede areal.
        /// </summary>
        
        [Column("byg041BebyggetAreal")]
        public virtual int? Byg041BebyggetAreal { get; set; }

        /// <summary>
        /// Angiver areal af indbygget garage.
        /// </summary>
        
        [Column("byg042ArealIndbyggetGarage")]
        public virtual int? Byg042ArealIndbyggetGarage { get; set; }

        /// <summary>
        /// Angiver areal af indbygget carport.
        /// </summary>
        
        [Column("byg043ArealIndbyggetCarport")]
        public virtual int? Byg043ArealIndbyggetCarport { get; set; }

        /// <summary>
        /// Angiver areal af indbygget udhus.
        /// </summary>
        
        [Column("byg044ArealIndbyggetUdhus")]
        public virtual int? Byg044ArealIndbyggetUdhus { get; set; }

        /// <summary>
        /// Angiver areal af indbygget udstue.
        /// </summary>
        
        [Column("byg045ArealIndbyggetUdestueEllerLign")]
        public virtual int? Byg045ArealIndbyggetUdestueEllerLign { get; set; }

        /// <summary>
        /// Angiver areal af lukkede overdækninger på hele bygningen.
        /// </summary>
        
        [Column("byg046SamletArealAfLukkedeOverdækningerPåBygningen")]
        public virtual int? Byg046SamletArealAfLukkedeOverdækningerPåBygningen { get; set; }

        /// <summary>
        /// Angiver areal af samtlige affaldsrum i terrænniveau.
        /// </summary>
        
        [Column("byg047ArealAfAffaldsrumITerrænniveau")]
        public virtual int? Byg047ArealAfAffaldsrumITerrænniveau { get; set; }

        /// <summary>
        /// Angiver andet areal i bygning.
        /// </summary>
        
        [Column("byg048AndetAreal")]
        public virtual int? Byg048AndetAreal { get; set; }

        /// <summary>
        /// Angiver arealet af overdækket areal på bygning.
        /// </summary>
        
        [Column("byg049ArealAfOverdækketAreal")]
        public virtual int? Byg049ArealAfOverdækketAreal { get; set; }

        /// <summary>
        /// Angiver det samlede areal af åbne overdækninger på bygningen.
        /// </summary>
        
        [Column("byg050ArealÅbneOverdækningerPåBygningenSamlet")]
        public virtual int? Byg050ArealÅbneOverdækningerPåBygningenSamlet { get; set; }

        /// <summary>
        /// Angiver det samlede adgangsareal på bygning.
        /// </summary>
        
        [Column("byg051Adgangsareal")]
        public virtual int? Byg051Adgangsareal { get; set; }

        /// <summary>
        /// Angiver beregningsprincip for areal af carport. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/BeregningsprincipForArealAfCarport">kodelisten.</a>
        /// </summary>
        
        [Column("byg052BeregningsprincipCarportAreal", TypeName = "varchar(1)")]
        public virtual string Byg052BeregningsprincipCarportAreal { get; set; }

        /// <summary>
        /// Angiver kilde til oplysninger om bygningens arealer. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KildeTilOplysninger">kodelisten.</a>
        /// </summary>
        
        [Column("byg053BygningsarealerKilde", TypeName = "varchar(1)")]
        public virtual string Byg053BygningsarealerKilde { get; set; }

        /// <summary>
        /// Angiver antal etager i bygningen.
        /// </summary>
        
        [Column("byg054AntalEtager")]
        public virtual int? Byg054AntalEtager { get; set; }

        /// <summary>
        /// Angiver om bygningen indeholder afvigende etager. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/AfvigendeEtager">kodelisten.</a>
        /// </summary>
        
        [Column("byg055AfvigendeEtager", TypeName = "varchar(2)")]
        public virtual string Byg055AfvigendeEtager { get; set; }

        /// <summary>
        /// Angiver bygningens primære varmeinstallation. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Varmeinstallation">kodelisten.</a>
        /// </summary>
        
        [Column("byg056Varmeinstallation", TypeName = "varchar(2)")]
        public virtual string Byg056Varmeinstallation { get; set; }

        /// <summary>
        /// Angiver bygningens primære opvarmingsmiddel. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Opvarmningsmiddel">kodelisten.</a>
        /// </summary>
        
        [Column("byg057Opvarmningsmiddel", TypeName = "varchar(1)")]
        public virtual string Byg057Opvarmningsmiddel { get; set; }

        /// <summary>
        /// Angiver supplerende varmeinstallation i bygningen. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/SupplerendeVarme">kodelisten.</a>
        /// </summary>
        
        [Column("byg058SupplerendeVarme", TypeName = "varchar(2)")]
        public virtual string Byg058SupplerendeVarme { get; set; }

        /// <summary>
        /// Angiver antallet at sikringsrumpladser i bygningen.
        /// 
        /// </summary>
        
        [Column("byg069Sikringsrumpladser")]
        public virtual int? Byg069Sikringsrumpladser { get; set; }

        /// <summary>
        /// Angiver om bygningen er fredet.
        ///  For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Fredning">kodelisten.</a>
        /// </summary>
        
        [Column("byg070Fredning", TypeName = "varchar(1)")]
        public virtual string Byg070Fredning { get; set; }

        /// <summary>
        /// Linker til Kulturstyrelsens registrering i FBB (Fredede og Bevaringsværdige Bygninger).
        /// </summary>
        
        [Column("byg071BevaringsværdighedReference", TypeName = "varchar(200)")]
        public virtual string Byg071BevaringsværdighedReference { get; set; }

        /// <summary>
        /// Angiver revisionsdato for seneste ændring af geometrioplysninger.
        /// </summary>
        
        [Column("byg094Revisionsdato")]
        public virtual DateTime? Byg094Revisionsdato { get; set; }

        /// <summary>
        /// Angiver selvrisiko ved stormskade. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Oversvoemmelsesselvrisiko">kodelisten.</a>
        /// </summary>
        
        [Column("byg111StormrådetsOversvømmelsesSelvrisiko", TypeName = "varchar(1)")]
        public virtual string Byg111StormrådetsOversvømmelsesSelvrisiko { get; set; }

        /// <summary>
        /// Angiver ajourføringsdato for registrering fra Stormrådet.
        /// </summary>
        
        [Column("byg112DatoForRegistreringFraStormrådet")]
        public virtual DateTime? Byg112DatoForRegistreringFraStormrådet { get; set; }

        /// <summary>
        /// Angiver navnet på byggeskadeforsikringsselskab For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Byggeskadeforsikringsselskab">kodelisten.</a>
        /// </summary>
        
        [Column("byg113Byggeskadeforsikringsselskab", TypeName = "varchar(2)")]
        public virtual string Byg113Byggeskadeforsikringsselskab { get; set; }

        /// <summary>
        /// Angiver ikræfttrædelsesdato for byggeskadeforsikring.
        /// </summary>
        
        [Column("byg114DatoForByggeskadeforsikring")]
        public virtual DateTime? Byg114DatoForByggeskadeforsikring { get; set; }

        /// <summary>
        /// Angiver status for udledningstilladelse på bygningen. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Udledningstilladelse">kodelisten.</a>
        /// </summary>
        
        [Column("byg119Udledningstilladelse", TypeName = "varchar(200)")]
        public virtual string Byg119Udledningstilladelse { get; set; }

        /// <summary>
        /// Angiver om bygningen er omfattet af byggeskadeforsikring. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/OmfattetAfByggeskadeforsikring">kodelisten.</a>
        /// </summary>
        
        [Column("byg121OmfattetAfByggeskadeforsikring", TypeName = "varchar(2)")]
        public virtual string Byg121OmfattetAfByggeskadeforsikring { get; set; }

        /// <summary>
        /// Angiver gyldighedsdato i forbindelse med vurdering.
        /// </summary>
        
        [Column("byg122Gyldighedsdato")]
        public virtual DateTime? Byg122Gyldighedsdato { get; set; }

        /// <summary>
        /// Angiver om der for bygningen er indgået kontraktligt medlemskab af spildevandsforsyningsselskab. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/MedlemsskabAfSplidevandforsyning">kodelisten.</a>
        /// </summary>
        
        [Column("byg123MedlemskabAfSpildevandsforsyning", TypeName = "varchar(1)")]
        public virtual string Byg123MedlemskabAfSpildevandsforsyning { get; set; }

        /// <summary>
        /// Angiver om der er givet påbud vedr. spildevandsafledning på bygningen. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Rensningspaabud">kodelisten.</a>
        /// </summary>
        
        [Column("byg124PåbudVedrSpildevandsafledning", TypeName = "varchar(1)")]
        public virtual string Byg124PåbudVedrSpildevandsafledning { get; set; }

        /// <summary>
        /// Angiver dato for frist for evt. påbud vedr. spildevandsafledning på bygningen.
        /// </summary>
        
        [Column("byg125FristVedrSpildevandsafledning")]
        public virtual DateTime? Byg125FristVedrSpildevandsafledning { get; set; }

        /// <summary>
        /// Angiver tilladelse til udtræden af det offentlige kloakfællesskab. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/TilladelseTilUdtraeden">kodelisten.</a>
        /// </summary>
        
        [Column("byg126TilladelseTilUdtræden", TypeName = "varchar(1)")]
        public virtual string Byg126TilladelseTilUdtræden { get; set; }

        /// <summary>
        /// Angiver dato for tilladelse til udtræden af det offentlige kloakfællesskab.
        /// </summary>
        
        [Column("byg127DatoForTilladelseTilUdtræden")]
        public virtual DateTime? Byg127DatoForTilladelseTilUdtræden { get; set; }

        /// <summary>
        /// Angiver tilladelse til alternativ bortskaffelse eller afledning af spildevand. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/TilladelseTilAlternativBortskaffelseEllerAfledning">kodelisten.</a>
        /// </summary>
        
        [Column("byg128TilladelseTilAlternativBortskaffelseEllerAfledning", TypeName = "varchar(1)")]
        public virtual string Byg128TilladelseTilAlternativBortskaffelseEllerAfledning { get; set; }

        /// <summary>
        /// Dato for tilladelse til alternativ bortskaffelse eller afledning af spildevand.
        /// </summary>
        
        [Column("byg129DatoForTilladelseTilAlternativBortskaffelseEllerAfledning")]
        public virtual DateTime? Byg129DatoForTilladelseTilAlternativBortskaffelseEllerAfledning { get; set; }

        /// <summary>
        /// Angiver areal af udvendig efterisolering.
        /// </summary>
        
        [Column("byg130ArealAfUdvendigEfterisolering")]
        public virtual int? Byg130ArealAfUdvendigEfterisolering { get; set; }

        /// <summary>
        /// Angiver om der er givet dispensation eller fritagelse ift kollektiv varmeforsyning. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/DispensationFritagelseIftKollektivVarmeforsyning">kodelisten.</a>
        /// </summary>
        
        [Column("byg131DispensationFritagelseIftKollektivVarmeforsyning", TypeName = "varchar(1)")]
        public virtual string Byg131DispensationFritagelseIftKollektivVarmeforsyning { get; set; }

        /// <summary>
        /// Angiver dato for dispensation eller fritagelse ift kollektiv varmeforsyning.
        /// </summary>
        
        [Column("byg132DatoForDispensationFritagelseIftKollektivVarmeforsyning")]
        public virtual DateTime? Byg132DatoForDispensationFritagelseIftKollektivVarmeforsyning { get; set; }

        /// <summary>
        /// Kodeliste der angiver kilden til geometrioplysninger. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KildeTilKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("byg133KildeTilKoordinatsæt", TypeName = "varchar(1)")]
        public virtual string Byg133KildeTilKoordinatsæt { get; set; }

        /// <summary>
        /// Kodeliste der angiver kvaliteten af geometrioplysninger. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KvalitetAfKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("byg134KvalitetAfKoordinatsæt", TypeName = "varchar(1)")]
        public virtual string Byg134KvalitetAfKoordinatsæt { get; set; }

        /// <summary>
        /// Angiver om det fysiske objekt koordinatsættet referer til ligger under eller over jorden. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/SupplerendeOplysningerOmKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("byg135SupplerendeOplysningOmKoordinatsæt", TypeName = "varchar(2)")]
        public virtual string Byg135SupplerendeOplysningOmKoordinatsæt { get; set; }

        /// <summary>
        /// Angiver om objekt ligger på søterritorie. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/PaaSoeTerritorie">kodelisten.</a>
        /// </summary>
        
        [Column("byg136PlaceringPåSøterritorie", TypeName = "varchar(1)")]
        public virtual string Byg136PlaceringPåSøterritorie { get; set; }

        /// <summary>
        /// Angiver Banedanmarks BGV-nummer og bygværksnummer
        /// </summary>
        
        [Column("byg137BanedanmarkBygværksnummer", TypeName = "varchar(200)")]
        public virtual string Byg137BanedanmarkBygværksnummer { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("byg140ServitutForUdlejningsEjendomDato")]
        public virtual DateTime? Byg140ServitutForUdlejningsEjendomDato { get; set; }

        /// <summary>
        /// Liste med koder vedrørende gulvbelægning For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Gulvbelaegning">kodelisten.</a>
        /// </summary>
        
        [Column("byg150Gulvbelægning", TypeName = "varchar(200)")]
        public virtual string Byg150Gulvbelægning { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("byg151Frihøjde")]
        public virtual double? Byg151Frihøjde { get; set; }

        /// <summary>
        /// Liste med koder vedrørende om en kontruktion er lukket eller åben For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Konstruktion">kodelisten.</a>
        /// </summary>
        
        [Column("byg152ÅbenLukketKonstruktion", TypeName = "varchar(1)")]
        public virtual string Byg152ÅbenLukketKonstruktion { get; set; }

        /// <summary>
        /// Liste med koder vedrørende konstruktionsforhold For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Konstruktionsforhold">kodelisten.</a>
        /// </summary>
        
        [Column("byg153Konstruktionsforhold", TypeName = "varchar(1)")]
        public virtual string Byg153Konstruktionsforhold { get; set; }

        /// <summary>
        /// Angiver den kommune bygningen flyttes til.
        /// </summary>
        
        [Column("byg302Tilflytterkommune")]
        public virtual int? Byg302Tilflytterkommune { get; set; }

        /// <summary>
        /// Angiver øvrige bemærkninger fra stormrådet.
        /// </summary>
        
        [Column("byg403ØvrigeBemærkningerFraStormrådet", TypeName = "varchar(200)")]
        public virtual string Byg403ØvrigeBemærkningerFraStormrådet { get; set; }

        /// <summary>
        /// Angiver bygningens geografiske reprsentation i form af et punkt.
        /// </summary>
        
        [Column("byg404Koordinat")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Byg404Koordinat { get; set; }

        /// <summary>
        /// Beskrivende tekstnotat om særlige forhold for dette BBR-element
        /// </summary>
        
        [Column("byg500Notatlinjer", TypeName = "varchar(max)")]
        public virtual string Byg500Notatlinjer { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Rowkey.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
