//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("bbr_enhed_historik")]
    public partial class Bbr_enhed_historik : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Bbr_enhed_historik()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Unik ID for den angivne række. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("rowkey")]
        [Required()]
        public virtual int Rowkey { get; set; }

        /// <summary>
        /// Startidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningstart")]
        [Required()]
        public virtual DateTime Virkningstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens virkningstid. 
        /// </summary>
        
        [Column("virkningslut")]
        public virtual DateTime? Virkningslut
        {
            get { return _Virkningslut.GetValueOrDefault(Defaults.Virkningslut); }
            set { _Virkningslut = value; }
        }
        private DateTime? _Virkningslut;

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Forretningshaendelse">kodelisten.</a>
        /// </summary>
        
        [Column("forretningshændelse", TypeName = "varchar(50)")]
        public virtual string Forretningshændelse { get; set; }

        /// <summary>
        /// FORM-kode for det offentlige forretningsområde som har opdateret bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsOmraade">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsområde", TypeName = "varchar(15)")]
        public virtual string Forretningsområde { get; set; }

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsProcess">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsproces", TypeName = "varchar(2)")]
        public virtual string Forretningsproces { get; set; }

        /// <summary>
        /// Unik og uforanderlig identifikation af bygværkselementet igennem hele dets livscyklus
        /// </summary>
        
        [Column("id")]
        public virtual Guid? Id { get; set; }

        /// <summary>
        /// Kode der identificerer den kommune som bygværkselementet hidhører For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Kommunekode">kodelisten.</a>
        /// </summary>
        
        [Column("kommunekode", TypeName = "varchar(4)")]
        public virtual string Kommunekode { get; set; }

        /// <summary>
        /// Kode som angiver hvilken aktør der har foretaget registreringen af den pågældende version af bygværkselementet
        /// </summary>
        
        [Column("registreringsaktør", TypeName = "varchar(90)")]
        public virtual string Registreringsaktør { get; set; }

        /// <summary>
        /// Kode for bygværkselementets status i den pågældende version, dvs. elementets tilstand i den samlede livscyklus For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Livscyklus">kodelisten.</a>
        /// </summary>
        
        [Column("status", TypeName = "varchar(2)")]
        public virtual string Status { get; set; }

        /// <summary>
        /// Kode for den aktør der har afstedkommet virkningsegenskaberne for den pågældende version af bygværkselementet For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Virkningsakt%C3%B8r">kodelisten.</a>
        /// </summary>
        
        [Column("virkningsaktør", TypeName = "varchar(90)")]
        public virtual string Virkningsaktør { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("adresseIdentificerer")]
        public virtual Guid? AdresseIdentificerer { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("etage")]
        public virtual Guid? Etage { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("opgang")]
        public virtual Guid? Opgang { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("bygning")]
        public virtual Guid? Bygning { get; set; }

        /// <summary>
        /// Angiver kode for enhedens anvendelse. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/EnhAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("enh020EnhedensAnvendelse", TypeName = "varchar(3)")]
        public virtual string Enh020EnhedensAnvendelse { get; set; }

        /// <summary>
        /// Angiver kode for boligtype. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Boligtype">kodelisten.</a>
        /// </summary>
        
        [Column("enh023Boligtype", TypeName = "varchar(1)")]
        public virtual string Enh023Boligtype { get; set; }

        /// <summary>
        /// Angiver kode for kondemneret boligenhed. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KondemneretBoligenhed">kodelisten.</a>
        /// </summary>
        
        [Column("enh024KondemneretBoligenhed", TypeName = "varchar(1)")]
        public virtual string Enh024KondemneretBoligenhed { get; set; }

        /// <summary>
        /// Angiver oprettelsesdato for enheden.
        /// </summary>
        
        [Column("enh025OprettelsesdatoForEnhedensIdentifikation")]
        public virtual DateTime? Enh025OprettelsesdatoForEnhedensIdentifikation { get; set; }

        /// <summary>
        /// Angiver enhedens samlede areal.
        /// </summary>
        
        [Column("enh026EnhedensSamledeAreal")]
        public virtual int? Enh026EnhedensSamledeAreal { get; set; }

        /// <summary>
        /// Angiver enhedens areal til beboelse.
        /// </summary>
        
        [Column("enh027ArealTilBeboelse")]
        public virtual int? Enh027ArealTilBeboelse { get; set; }

        /// <summary>
        /// Angiver enhedens areal til erhverv.
        /// </summary>
        
        [Column("enh028ArealTilErhverv")]
        public virtual int? Enh028ArealTilErhverv { get; set; }

        /// <summary>
        /// Angiver kode for kilde til oplysninger om areal. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KildeTilOplysninger">kodelisten.</a>
        /// </summary>
        
        [Column("enh030KildeTilEnhedensArealer", TypeName = "varchar(1)")]
        public virtual string Enh030KildeTilEnhedensArealer { get; set; }

        /// <summary>
        /// Angiver antal værelser i enheden.
        /// </summary>
        
        [Column("enh031AntalVærelser")]
        public virtual int? Enh031AntalVærelser { get; set; }

        /// <summary>
        /// Angiver kode for enhedens toiletforhold. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Toiletforhold">kodelisten.</a>
        /// </summary>
        
        [Column("enh032Toiletforhold", TypeName = "varchar(1)")]
        public virtual string Enh032Toiletforhold { get; set; }

        /// <summary>
        /// Angiver kode for enhedens badeforhold. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Badeforhold">kodelisten.</a>
        /// </summary>
        
        [Column("enh033Badeforhold", TypeName = "varchar(1)")]
        public virtual string Enh033Badeforhold { get; set; }

        /// <summary>
        /// Angiver kode for enhedens køkkenforhold. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Koekkenforhold">kodelisten.</a>
        /// </summary>
        
        [Column("enh034Køkkenforhold", TypeName = "varchar(1)")]
        public virtual string Enh034Køkkenforhold { get; set; }

        /// <summary>
        /// Angiver kode for enhedens energiforsyning. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Energiforsyning">kodelisten.</a>
        /// </summary>
        
        [Column("enh035Energiforsyning", TypeName = "varchar(1)")]
        public virtual string Enh035Energiforsyning { get; set; }

        /// <summary>
        /// Angiver enhedens andet areal
        /// </summary>
        
        [Column("enh039AndetAreal")]
        public virtual int? Enh039AndetAreal { get; set; }

        /// <summary>
        /// Angiver eventuel dispensation til anvendelse af enheden For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/LovligAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("enh041LovligAnvendelse", TypeName = "varchar(1)")]
        public virtual string Enh041LovligAnvendelse { get; set; }

        /// <summary>
        /// Angiver dato for tidsbegrænset dispensation.
        /// </summary>
        
        [Column("enh042DatoForTidsbegrænsetDispensation")]
        public virtual DateTime? Enh042DatoForTidsbegrænsetDispensation { get; set; }

        /// <summary>
        /// Angiver dato for delvis ibrugtagningstilladelse.
        /// </summary>
        
        [Column("enh044DatoForDelvisIbrugtagningsTilladelse")]
        public virtual DateTime? Enh044DatoForDelvisIbrugtagningsTilladelse { get; set; }

        /// <summary>
        /// Angiver enhedens udlejningsforhold For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Udlejningsforhold">kodelisten.</a>
        /// </summary>
        
        [Column("enh045Udlejningsforhold", TypeName = "varchar(200)")]
        public virtual string Enh045Udlejningsforhold { get; set; }

        /// <summary>
        /// Angiver offentlig støtte. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/OffentligStoette">kodelisten.</a>
        /// </summary>
        
        [Column("enh046OffentligStøtte", TypeName = "varchar(2)")]
        public virtual string Enh046OffentligStøtte { get; set; }

        /// <summary>
        /// Angiver dato for indflytning.
        /// </summary>
        
        [Column("enh047IndflytningDato")]
        public virtual DateTime? Enh047IndflytningDato { get; set; }

        /// <summary>
        /// Angiver om boligen er godkendt som tom bolig For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/GodkendtTomBolig">kodelisten.</a>
        /// </summary>
        
        [Column("enh048GodkendtTomBolig", TypeName = "varchar(3)")]
        public virtual string Enh048GodkendtTomBolig { get; set; }

        /// <summary>
        /// Angiver enhedens varmeinstallation. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Varmeinstallation">kodelisten.</a>
        /// </summary>
        
        [Column("enh051Varmeinstallation", TypeName = "varchar(1)")]
        public virtual string Enh051Varmeinstallation { get; set; }

        /// <summary>
        /// Angiver enhedens opvarmningsmiddel. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Opvarmningsmiddel">kodelisten.</a>
        /// </summary>
        
        [Column("enh052Opvarmningsmiddel", TypeName = "varchar(200)")]
        public virtual string Enh052Opvarmningsmiddel { get; set; }

        /// <summary>
        /// Angiver enhedens supplerende varme. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/SupplerendeVarme">kodelisten.</a>
        /// </summary>
        
        [Column("enh053SupplerendeVarme", TypeName = "varchar(2)")]
        public virtual string Enh053SupplerendeVarme { get; set; }

        /// <summary>
        /// Angiver enhedens andel i fælles adgangsareal.
        /// </summary>
        
        [Column("enh060EnhedensAndelFællesAdgangsareal")]
        public virtual int? Enh060EnhedensAndelFællesAdgangsareal { get; set; }

        /// <summary>
        /// Angiver enhedens areal af åben overdækning.
        /// </summary>
        
        [Column("enh061ArealAfÅbenOverdækning")]
        public virtual int? Enh061ArealAfÅbenOverdækning { get; set; }

        /// <summary>
        /// Angiver enhedens areal af lukket overdækning.
        /// </summary>
        
        [Column("enh062ArealAfLukketOverdækningUdestue")]
        public virtual int? Enh062ArealAfLukketOverdækningUdestue { get; set; }

        /// <summary>
        /// Angiver antal værelser i enheden der anvendes til erhverv.
        /// 
        /// </summary>
        
        [Column("enh063AntalVærelserTilErhverv")]
        public virtual int? Enh063AntalVærelserTilErhverv { get; set; }

        /// <summary>
        /// Angiver antal vandskyllende toiletter.
        /// </summary>
        
        [Column("enh065AntalVandskylledeToiletter")]
        public virtual int? Enh065AntalVandskylledeToiletter { get; set; }

        /// <summary>
        /// Angiver antal badeværeslser.
        /// </summary>
        
        [Column("enh066AntalBadeværelser")]
        public virtual int? Enh066AntalBadeværelser { get; set; }

        /// <summary>
        /// Angiver årstal for støjisolering.
        /// </summary>
        
        [Column("enh067Støjisolering")]
        public virtual int? Enh067Støjisolering { get; set; }

        /// <summary>
        /// Liste med koder vedrørende arten af tilladelse For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Tilladelsesart">kodelisten.</a>
        /// </summary>
        
        [Column("enh068FlexboligTilladelsesart", TypeName = "varchar(1)")]
        public virtual string Enh068FlexboligTilladelsesart { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enh069FlexboligOphørsdato")]
        public virtual DateTime? Enh069FlexboligOphørsdato { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enh070ÅbenAltanTagterrasseAreal")]
        public virtual int? Enh070ÅbenAltanTagterrasseAreal { get; set; }

        /// <summary>
        /// Liste med koder vedrørende adressens funktion i forhold til enheden For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/AdresseRolle">kodelisten.</a>
        /// </summary>
        
        [Column("enh071AdresseFunktion", TypeName = "varchar(1)")]
        public virtual string Enh071AdresseFunktion { get; set; }

        /// <summary>
        /// Angvier gyldighedsdato for enheden
        /// </summary>
        
        [Column("enh101Gyldighedsdato")]
        public virtual DateTime? Enh101Gyldighedsdato { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enh102HerafAreal1")]
        public virtual int? Enh102HerafAreal1 { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enh103HerafAreal2")]
        public virtual int? Enh103HerafAreal2 { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enh104HerafAreal3")]
        public virtual int? Enh104HerafAreal3 { get; set; }

        /// <summary>
        /// Liste med koder vedrørende anvendelse For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/EnhAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("enh105SupplerendeAnvendelseskode1", TypeName = "varchar(3)")]
        public virtual string Enh105SupplerendeAnvendelseskode1 { get; set; }

        /// <summary>
        /// Liste med koder vedrørende anvendelse For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/EnhAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("enh106SupplerendeAnvendelseskode2", TypeName = "varchar(3)")]
        public virtual string Enh106SupplerendeAnvendelseskode2 { get; set; }

        /// <summary>
        /// Liste med koder vedrørende anvendelse For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/EnhAnvendelse">kodelisten.</a>
        /// </summary>
        
        [Column("enh107SupplerendeAnvendelseskode3", TypeName = "varchar(3)")]
        public virtual string Enh107SupplerendeAnvendelseskode3 { get; set; }

        /// <summary>
        /// Angiver enhedens fysiske areal til beboelse.
        /// </summary>
        
        [Column("enh127FysiskArealTilBeboelse")]
        public virtual int? Enh127FysiskArealTilBeboelse { get; set; }

        /// <summary>
        /// Angiver enhedens fysiske areal til erhverv.
        /// </summary>
        
        [Column("enh128FysiskArealTilErhverv")]
        public virtual int? Enh128FysiskArealTilErhverv { get; set; }

        /// <summary>
        /// Beskrivende tekstnotat om særlige forhold for dette BBR-element
        /// </summary>
        
        [Column("enh500Notatlinjer", TypeName = "varchar(max)")]
        public virtual string Enh500Notatlinjer { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Rowkey.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
