//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("bbr_tekniskanlæg")]
    public partial class Bbr_tekniskanlæg : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Bbr_tekniskanlæg()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Unik ID for den angivne række. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("rowkey")]
        [Required()]
        public virtual int Rowkey { get; set; }

        /// <summary>
        /// Startidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningstart")]
        [Required()]
        public virtual DateTime Virkningstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens virkningstid. 
        /// </summary>
        
        [Column("virkningslut")]
        public virtual DateTime? Virkningslut
        {
            get { return _Virkningslut.GetValueOrDefault(Defaults.Virkningslut); }
            set { _Virkningslut = value; }
        }
        private DateTime? _Virkningslut;

        /// <summary>
        /// Startidspunktet for rækkens registreringstid.
        /// </summary>
        
        [Column("registreringstart")]
        [Required()]
        public virtual DateTime Registreringstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens registreringstid. 
        /// </summary>
        
        [Column("registreringslut")]
        public virtual DateTime? Registreringslut
        {
            get { return _Registreringslut.GetValueOrDefault(Defaults.Registreringslut); }
            set { _Registreringslut = value; }
        }
        private DateTime? _Registreringslut;

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Forretningshaendelse">kodelisten.</a>
        /// </summary>
        
        [Column("forretningshændelse", TypeName = "varchar(50)")]
        public virtual string Forretningshændelse { get; set; }

        /// <summary>
        /// FORM-kode for det offentlige forretningsområde som har opdateret bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsOmraade">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsområde", TypeName = "varchar(15)")]
        public virtual string Forretningsområde { get; set; }

        /// <summary>
        /// Kode for den forretningshændelse, som afstedkom opdateringen af bygværkselementet til den pågældende version For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/ForretningsProcess">kodelisten.</a>
        /// </summary>
        
        [Column("forretningsproces", TypeName = "varchar(2)")]
        public virtual string Forretningsproces { get; set; }

        /// <summary>
        /// Unik og uforanderlig identifikation af bygværkselementet igennem hele dets livscyklus
        /// </summary>
        
        [Column("id")]
        public virtual Guid? Id { get; set; }

        /// <summary>
        /// Kode der identificerer den kommune som bygværkselementet hidhører For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Kommunekode">kodelisten.</a>
        /// </summary>
        
        [Column("kommunekode", TypeName = "varchar(4)")]
        public virtual string Kommunekode { get; set; }

        /// <summary>
        /// Kode som angiver hvilken aktør der har foretaget registreringen af den pågældende version af bygværkselementet
        /// </summary>
        
        [Column("registreringsaktør", TypeName = "varchar(90)")]
        public virtual string Registreringsaktør { get; set; }

        /// <summary>
        /// Kode for bygværkselementets status i den pågældende version, dvs. elementets tilstand i den samlede livscyklus For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Livscyklus">kodelisten.</a>
        /// </summary>
        
        [Column("status", TypeName = "varchar(2)")]
        public virtual string Status { get; set; }

        /// <summary>
        /// Kode for den aktør der har afstedkommet virkningsegenskaberne for den pågældende version af bygværkselementet For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Virkningsakt%C3%B8r">kodelisten.</a>
        /// </summary>
        
        [Column("virkningsaktør", TypeName = "varchar(90)")]
        public virtual string Virkningsaktør { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("jordstykke")]
        public virtual int? Jordstykke { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("husnummer")]
        public virtual Guid? Husnummer { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("enhed")]
        public virtual Guid? Enhed { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("ejerlejlighed")]
        public virtual Guid? Ejerlejlighed { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("bygningPåFremmedGrund")]
        public virtual Guid? BygningPåFremmedGrund { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("bygning")]
        public virtual Guid? Bygning { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("grund")]
        public virtual Guid? Grund { get; set; }

        /// <summary>
        /// Angiver løbenummer under vurderingsejendommen
        /// </summary>
        
        [Column("tek007Anlægsnummer")]
        public virtual int? Tek007Anlægsnummer { get; set; }

        /// <summary>
        /// Angiver det tekniske anlægs anvendelse. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Klassifikation">kodelisten.</a>
        /// </summary>
        
        [Column("tek020Klassifikation", TypeName = "varchar(4)")]
        public virtual string Tek020Klassifikation { get; set; }

        /// <summary>
        /// Angiver det tekniske anlægs fabrikattype.
        /// </summary>
        
        [Column("tek021FabrikatType", TypeName = "varchar(200)")]
        public virtual string Tek021FabrikatType { get; set; }

        /// <summary>
        /// Angivelse af reference til ekstern database.
        /// </summary>
        
        [Column("tek022EksternDatabase", TypeName = "varchar(200)")]
        public virtual string Tek022EksternDatabase { get; set; }

        /// <summary>
        /// Angiver unik teknisk nøgle til det tekniske anlæg.
        /// </summary>
        
        [Column("tek023EksternNøgle", TypeName = "varchar(200)")]
        public virtual string Tek023EksternNøgle { get; set; }

        /// <summary>
        /// Angiverå år for færdigetablering.
        /// </summary>
        
        [Column("tek024Etableringsår")]
        public virtual int? Tek024Etableringsår { get; set; }

        /// <summary>
        /// Angiver til/ombygningsår for det tekniske anlæg
        /// </summary>
        
        [Column("tek025TilOmbygningsår")]
        public virtual int? Tek025TilOmbygningsår { get; set; }

        /// <summary>
        /// Angiver størrelsesklasse af olietank. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Stoerrelsesklasse">kodelisten.</a>
        /// </summary>
        
        [Column("tek026StørrelsesklasseOlietank", TypeName = "varchar(1)")]
        public virtual string Tek026StørrelsesklasseOlietank { get; set; }

        /// <summary>
        /// Angivelse af placering af tank, silo, gas- og affaldsbeholder. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Placering">kodelisten.</a>
        /// </summary>
        
        [Column("tek027Placering", TypeName = "varchar(1)")]
        public virtual string Tek027Placering { get; set; }

        /// <summary>
        /// Angiver forhold for sløjfning af olietank. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Sloejfning">kodelisten.</a>
        /// </summary>
        
        [Column("tek028SløjfningOlietank", TypeName = "varchar(2)")]
        public virtual string Tek028SløjfningOlietank { get; set; }

        /// <summary>
        /// Tankens fabrikationsnummer.
        /// </summary>
        
        [Column("tek030Fabrikationsnummer", TypeName = "varchar(200)")]
        public virtual string Tek030Fabrikationsnummer { get; set; }

        /// <summary>
        /// Angiver typegodkendelse af tank.
        /// </summary>
        
        [Column("tek031Typegodkendelsesnummer", TypeName = "varchar(200)")]
        public virtual string Tek031Typegodkendelsesnummer { get; set; }

        /// <summary>
        /// Angiver tankens størrelse..
        /// </summary>
        
        [Column("tek032Størrelse")]
        public virtual int? Tek032Størrelse { get; set; }

        /// <summary>
        /// Angiver olietantkens type. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/TypeAfVaegge">kodelisten.</a>
        /// </summary>
        
        [Column("tek033Type", TypeName = "varchar(1)")]
        public virtual string Tek033Type { get; set; }

        /// <summary>
        /// Angiver tankens/olietankens Indhold For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Indhold">kodelisten.</a>
        /// </summary>
        
        [Column("tek034IndholdOlietank", TypeName = "varchar(2)")]
        public virtual string Tek034IndholdOlietank { get; set; }

        /// <summary>
        /// Angiver dato for frist for sløjfning af tank.
        /// </summary>
        
        [Column("tek035SløjfningsfristOlietank")]
        public virtual DateTime? Tek035SløjfningsfristOlietank { get; set; }

        /// <summary>
        /// Angiver rumfang af teknisk anlæg.
        /// </summary>
        
        [Column("tek036Rumfang")]
        public virtual int? Tek036Rumfang { get; set; }

        /// <summary>
        /// Angiver det bebyggede areal af teknisk anlæg.
        /// </summary>
        
        [Column("tek037Areal")]
        public virtual int? Tek037Areal { get; set; }

        /// <summary>
        /// Angiver det tekniske anlægs højde.
        /// </summary>
        
        [Column("tek038Højde")]
        public virtual int? Tek038Højde { get; set; }

        /// <summary>
        /// Angiver effekt for et energiproducerende teknisk anlæg.
        /// </summary>
        
        [Column("tek039Effekt")]
        public virtual int? Tek039Effekt { get; set; }

        /// <summary>
        /// Angiver eventuel type af fredning der gælder for det teknisk anlæg. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Fredning">kodelisten.</a>
        /// </summary>
        
        [Column("tek040Fredning", TypeName = "varchar(1)")]
        public virtual string Tek040Fredning { get; set; }

        /// <summary>
        /// Angiver revisionsdato for seneste ændring af geometrioplysninger.
        /// </summary>
        
        [Column("tek042Revisionsdato")]
        public virtual DateTime? Tek042Revisionsdato { get; set; }

        /// <summary>
        /// Angiver geografisk koordinatsystem og projektion. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Koordinatsystem">kodelisten.</a>
        /// </summary>
        
        [Column("tek045Koordinatsystem", TypeName = "varchar(1)")]
        public virtual string Tek045Koordinatsystem { get; set; }

        /// <summary>
        /// Angiver fabrikationsår for tanke.
        /// </summary>
        
        [Column("tek067Fabrikationsår")]
        public virtual int? Tek067Fabrikationsår { get; set; }

        /// <summary>
        /// Angiver det materiale tanken er lavet af. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Materiale">kodelisten.</a>
        /// </summary>
        
        [Column("tek068Materiale", TypeName = "varchar(1)")]
        public virtual string Tek068Materiale { get; set; }

        /// <summary>
        /// Angiver type af senest udførte supplerende invendig korresionsbeskyttelse. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/SupplerendeIndvendigKorrosionsbeskyttelse">kodelisten.</a>
        /// </summary>
        
        [Column("tek069SupplerendeIndvendigKorrosionsbeskyttelse", TypeName = "varchar(1)")]
        public virtual string Tek069SupplerendeIndvendigKorrosionsbeskyttelse { get; set; }

        /// <summary>
        /// Angiver dato for den senest udførte indvendige korrosionsbeskyttelse.
        /// </summary>
        
        [Column("tek070DatoForSenestUdførteSupplerendeIndvendigKorrosionsbeskyttelse")]
        public virtual DateTime? Tek070DatoForSenestUdførteSupplerendeIndvendigKorrosionsbeskyttelse { get; set; }

        /// <summary>
        /// Angiver årstal for sløjfning af tank.
        /// </summary>
        
        [Column("tek072Sløjfningsår")]
        public virtual int? Tek072Sløjfningsår { get; set; }

        /// <summary>
        /// Angiver vindmøllens højde ved navet.
        /// </summary>
        
        [Column("tek073Navhøjde")]
        public virtual double? Tek073Navhøjde { get; set; }

        /// <summary>
        /// Angiver den unikke identifikation af vindmøllen.
        /// </summary>
        
        [Column("tek074Vindmøllenummer", TypeName = "varchar(40)")]
        public virtual string Tek074Vindmøllenummer { get; set; }

        /// <summary>
        /// Angiver diameteren for rotoren på vindmøllen.
        /// </summary>
        
        [Column("tek075Rotordiameter")]
        public virtual double? Tek075Rotordiameter { get; set; }

        /// <summary>
        /// Angiver kilden til geometrioplysninger. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KildeTilKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("tek076KildeTilKoordinatsæt", TypeName = "varchar(1)")]
        public virtual string Tek076KildeTilKoordinatsæt { get; set; }

        /// <summary>
        /// Angiver kvaliteten af geometrioplysninger. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/KvalitetAfKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("tek077KvalitetAfKoordinatsæt", TypeName = "varchar(1)")]
        public virtual string Tek077KvalitetAfKoordinatsæt { get; set; }

        /// <summary>
        /// Angiver om det fysiske objekt, koordinatsættet referer til ligger under eller over jorden. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/SupplerendeOplysningerOmKoordinatsaet">kodelisten.</a>
        /// </summary>
        
        [Column("tek078SupplerendeOplysningOmKoordinatsæt", TypeName = "varchar(2)")]
        public virtual string Tek078SupplerendeOplysningOmKoordinatsæt { get; set; }

        /// <summary>
        /// Angiver gyldighedsdato i forbindelse med vurdering.
        /// </summary>
        
        [Column("tek101Gyldighedsdato")]
        public virtual DateTime? Tek101Gyldighedsdato { get; set; }

        /// <summary>
        /// Angiver fabrikat på vindmølle.
        /// </summary>
        
        [Column("tek102FabrikatVindmølle", TypeName = "varchar(200)")]
        public virtual string Tek102FabrikatVindmølle { get; set; }

        /// <summary>
        /// Angiver fabrikat på oliefyr.
        /// </summary>
        
        [Column("tek103FabrikatOliefyr", TypeName = "varchar(200)")]
        public virtual string Tek103FabrikatOliefyr { get; set; }

        /// <summary>
        /// Angiver fabrikat på solcelleanlæg eller solvarmeanlæg.
        /// </summary>
        
        [Column("tek104FabrikatSolcelleanlægSolvarme", TypeName = "varchar(200)")]
        public virtual string Tek104FabrikatSolcelleanlægSolvarme { get; set; }

        /// <summary>
        /// Angiver om tanken er overdækket.
        /// </summary>
        
        [Column("tek105OverdækningTank", TypeName = "varchar(200)")]
        public virtual string Tek105OverdækningTank { get; set; }

        /// <summary>
        /// Angiver dato for inspektion af tank.
        /// </summary>
        
        [Column("tek106InspektionsdatoTank")]
        public virtual DateTime? Tek106InspektionsdatoTank { get; set; }

        /// <summary>
        /// Angiver om teknisk anlæg ligger på søterritorie. For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/PaaSoeTerritorie">kodelisten.</a>
        /// </summary>
        
        [Column("tek107PlaceringPåSøterritorie", TypeName = "varchar(1)")]
        public virtual string Tek107PlaceringPåSøterritorie { get; set; }

        /// <summary>
        /// Angiver det tekniske areals geografiske placering
        /// </summary>
        
        [Column("tek109Koordinat")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Tek109Koordinat { get; set; }

        /// <summary>
        /// Liste med koder vedrørende et anlægs driftsstatus For mulige værdier, se <a href="https://ki.bbr.dk/kodelister-bbr/0/1/0/Driftstatus">kodelisten.</a>
        /// </summary>
        
        [Column("tek110Driftstatus", TypeName = "varchar(1)")]
        public virtual string Tek110Driftstatus { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("tek111DatoForSenesteInspektion")]
        public virtual DateTime? Tek111DatoForSenesteInspektion { get; set; }

        /// <summary>
        /// 
        /// </summary>
        
        [Column("tek112InspicerendeVirksomhed", TypeName = "varchar(200)")]
        public virtual string Tek112InspicerendeVirksomhed { get; set; }

        /// <summary>
        /// Beskrivende tekstnotat om særlige forhold for dette BBR-element
        /// </summary>
        
        [Column("tek500Notatlinjer", TypeName = "varchar(max)")]
        public virtual string Tek500Notatlinjer { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Rowkey.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
