//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("dar_husnummer_aktuel")]
    public partial class Dar_husnummer_aktuel : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Dar_husnummer_aktuel()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Ikke tilgængelig
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("id")]
        [Required()]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("status")]
        [Required()]
        public virtual int Status { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("adgangspunkt_id")]
        [Required()]
        public virtual Guid Adgangspunkt_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("darafstemningsområde_id")]
        [Required()]
        public virtual Guid Darafstemningsområde_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("darkommune_id")]
        [Required()]
        public virtual Guid Darkommune_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("darmenighedsrådsafstemningsområde_id")]
        public virtual Guid? Darmenighedsrådsafstemningsområde_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("darsogneinddeling_id")]
        [Required()]
        public virtual Guid Darsogneinddeling_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_bbr_bygning_adgangtilbygning", TypeName = "varchar(36)")]
        public virtual string Fk_bbr_bygning_adgangtilbygning { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_bbr_tekniskanlæg_adgangtiltekniskanlæg", TypeName = "varchar(36)")]
        public virtual string Fk_bbr_tekniskanlæg_adgangtiltekniskanlæg { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_geodk_bygning_geodanmarkbygning", TypeName = "varchar(200)")]
        public virtual string Fk_geodk_bygning_geodanmarkbygning { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_geodk_vejmidte_vejmidte", TypeName = "varchar(200)")]
        public virtual string Fk_geodk_vejmidte_vejmidte { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_mu_jordstykke_foreløbigtplaceretpåjordstykke", TypeName = "varchar(200)")]
        public virtual string Fk_mu_jordstykke_foreløbigtplaceretpåjordstykke { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("fk_mu_jordstykke_jordstykke", TypeName = "varchar(200)")]
        public virtual string Fk_mu_jordstykke_jordstykke { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("husnummerretning")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Husnummerretning { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("husnummertekst", TypeName = "varchar(200)")]
        public virtual string Husnummertekst { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("navngivenvej_id")]
        public virtual Guid? Navngivenvej_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("postnummer_id")]
        [Required()]
        public virtual Guid Postnummer_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("supplerendebynavn_id")]
        public virtual Guid? Supplerendebynavn_id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejpunkt_id")]
        [Required()]
        public virtual Guid Vejpunkt_id { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Id.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
