//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("dar_navngivenvej_historik")]
    public partial class Dar_navngivenvej_historik : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Dar_navngivenvej_historik()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Unik ID for den angivne række. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("rowkey")]
        [Required()]
        public virtual int Rowkey { get; set; }

        /// <summary>
        /// Startidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningstart")]
        [Required()]
        public virtual DateTime Virkningstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens virkningstid. 
        /// </summary>
        
        [Column("virkningslut")]
        public virtual DateTime? Virkningslut { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("id")]
        [Required()]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("status")]
        [Required()]
        public virtual int Status { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("administreresafkommune", TypeName = "varchar(4)")]
        public virtual string Administreresafkommune { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("beskrivelse", TypeName = "varchar(1000)")]
        public virtual string Beskrivelse { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("retskrivningskontrol", TypeName = "varchar(40)")]
        public virtual string Retskrivningskontrol { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("udtaltvejnavn", TypeName = "varchar(80)")]
        public virtual string Udtaltvejnavn { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejadresseringsnavn", TypeName = "varchar(20)")]
        public virtual string Vejadresseringsnavn { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavn", TypeName = "varchar(40)")]
        public virtual string Vejnavn { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_oprindelse_kilde", TypeName = "varchar(20)")]
        public virtual string Vejnavnebeliggenhed_oprindelse_kilde { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_oprindelse_nøjagtighedsklasse", TypeName = "varchar(1)")]
        public virtual string Vejnavnebeliggenhed_oprindelse_nøjagtighedsklasse { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_oprindelse_registrering")]
        [Required()]
        public virtual DateTime Vejnavnebeliggenhed_oprindelse_registrering { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_oprindelse_tekniskstandard", TypeName = "varchar(20)")]
        public virtual string Vejnavnebeliggenhed_oprindelse_tekniskstandard { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_vejnavnelinje")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Vejnavnebeliggenhed_vejnavnelinje { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_vejnavneområde")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Vejnavnebeliggenhed_vejnavneområde { get; set; }

        /// <summary>
        /// Ikke tilgængelig
        /// </summary>
        
        [Column("vejnavnebeliggenhed_vejtilslutningspunkter")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Vejnavnebeliggenhed_vejtilslutningspunkter { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Rowkey.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
