//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("højde")]
    public partial class Højde : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Højde()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Husnummeret (adgangsadressen), hvis adgangspunkt som rækken angiver højden på
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("husnummerid")]
        [Required()]
        public virtual Guid Husnummerid { get; set; }

        /// <summary>
        /// Adgangspunktets højde i meter over havoverfladen. Beregnet ud fra Danmarks Højdemodel. Værdien -9999 angiver, at højden er udenfor højdemodellen, og derfor ikke kan beregnes.
        /// </summary>
        
        [Column("højde")]
        [Required()]
        [JsonProperty(PropertyName = "højde")]
        public virtual double Højde_ { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Husnummerid.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
