//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("stedtilknytning")]
    public partial class Stedtilknytning : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Stedtilknytning()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER EN DEL AF PKEY. stedets ID
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("stedid", Order = 0)]
        [Required()]
        public virtual Guid Stedid { get; set; }

        /// <summary>
        /// DETTE ER EN DEL AF PKEY. adgangsadressens ID
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("adgangsadresseid", Order = 1)]
        [Required()]
        public virtual Guid Adgangsadresseid { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Stedid.ToString() + "_" + Adgangsadresseid.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
