//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("vask_husnummer_historik")]
    public partial class Vask_husnummer_historik : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Vask_husnummer_historik()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Rækkens unikke ID
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("rowkey")]
        [Required()]
        public virtual int Rowkey { get; set; }

        /// <summary>
        /// Adressens ID.
        /// </summary>
        
        [Column("id")]
        [Required()]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Adgangspunktets status
        /// </summary>
        
        [Column("adgangspunkt_status")]
        public virtual int? Adgangspunkt_status { get; set; }

        /// <summary>
        /// Husnummerets status.
        /// </summary>
        
        [Column("husnummer_status")]
        [Required()]
        public virtual int Husnummer_status { get; set; }

        /// <summary>
        /// Kommunekoden. 4 cifre.
        /// </summary>
        
        [Column("kommunekode", TypeName = "varchar(4)")]
        [Required()]
        public virtual string Kommunekode { get; set; }

        /// <summary>
        /// Vejkoden. 4 cifre.
        /// </summary>
        
        [Column("vejkode", TypeName = "varchar(4)")]
        [Required()]
        public virtual string Vejkode { get; set; }

        /// <summary>
        /// Adressens vejnavn.
        /// </summary>
        
        [Column("vejnavn", TypeName = "varchar(40)")]
        [Required()]
        public virtual string Vejnavn { get; set; }

        /// <summary>
        /// En evt. forkortet udgave af adressens vejnavn.
        /// </summary>
        
        [Column("adresseringsvejnavn", TypeName = "varchar(20)")]
        [Required()]
        public virtual string Adresseringsvejnavn { get; set; }

        /// <summary>
        /// Adressens husnummer. Tal samt evt. bogstav.
        /// </summary>
        
        [Column("husnr", TypeName = "varchar(4)")]
        [Required()]
        public virtual string Husnr { get; set; }

        /// <summary>
        /// Et supplerende bynavn – typisk landsbyens navn – eller andet lokalt stednavn.
        /// </summary>
        
        [Column("supplerendebynavn", TypeName = "varchar(50)")]
        public virtual string Supplerendebynavn { get; set; }

        /// <summary>
        /// Adressens postnummer.
        /// </summary>
        
        [Column("postnr", TypeName = "varchar(4)")]
        [Required()]
        public virtual string Postnr { get; set; }

        /// <summary>
        /// Det navn der er knyttet til postnummeret, typisk byens eller bydelens navn.
        /// </summary>
        
        [Column("postnrnavn", TypeName = "varchar(20)")]
        [Required()]
        public virtual string Postnrnavn { get; set; }

        /// <summary>
        /// Startidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningstart")]
        [Required()]
        public virtual DateTime Virkningstart { get; set; }

        /// <summary>
        /// Sluttidspunktet for rækkens virkningstid.
        /// </summary>
        
        [Column("virkningslut")]
        public virtual DateTime? Virkningslut { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Rowkey.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
