//-----------------------------------------------------------------------------------------------
// This is auto-generated code.
//-----------------------------------------------------------------------------------------------
// This code was generated by JO Informatik DAWA Replication tool version 1.0.2.0
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------
using Microsoft.SqlServer.Types;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JOInformatik.DawaReplication.DataAccess
{
    /// <summary>TODO.</summary>
    [GeneratedCode("JO Informatik DAWA Replication tool", "version 1.0.2.0")]
    [Table("vejpunkt")]
    public partial class Vejpunkt : ReplicationBase
    {
        /// <summary>This constructor calls OnCreated().</summary>
        public Vejpunkt()
        {
            EntityUpdated = DateTime.Now;
            OnCreated();
        }

        /// <summary>
        /// DETTE ER PKEY. Vejpunktets unikke ID.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None), Column("id")]
        [Required()]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Vejpunktets kilde.
        /// </summary>
        
        [Column("kilde", TypeName = "varchar(10)")]
        [Required()]
        public virtual string Kilde { get; set; }

        /// <summary>
        /// Vejpunktets tekniske standard.
        /// </summary>
        
        [Column("tekniskstandard", TypeName = "varchar(2)")]
        [Required()]
        public virtual string Tekniskstandard { get; set; }

        /// <summary>
        /// Vejpunktets nøjagtighedsklasse.
        /// </summary>
        
        [Column("nøjagtighedsklasse", TypeName = "varchar(1)")]
        [Required()]
        public virtual string Nøjagtighedsklasse { get; set; }

        /// <summary>
        /// Vejpunktets position.
        /// </summary>
        
        [Column("position")]
        [JsonConverter(typeof(SqlGeometryConverter))]
        public virtual SqlGeometry Position { get; set; }

        /// <summary>Overwrite this method to do your own initialization of the entity.</summary>
        partial void OnCreated();

        /// Returns the primary key as a string (includes all columns).</summary>
        public override string DawaPkey
        {
            get
            {
                if (_dawaPkey == null)
                {
                    _dawaPkey = Id.ToString();
                }
                return _dawaPkey;
            }
        }

        [Column("entity_updated")]
        [Required()]
        /// <summary>Tidspunktet da rækken blev oprettet eller ændret i databasen hos JOI.</summary>
        public DateTime EntityUpdated { get; set; }

    }
}
